### ISSUE TITLE
Eigenvalues section and symmetric matrices

### ISSUE THREAD

**Issue by IanHawke** [patrickwalls/mathematical-python#4]
In the Examples subsection of the Eigenvalues and Eigenvectors section (in Linear Algebra), you state "Create the symmetric matrix $S = P + P^T$", but the code creates $S = P P^T$ (matrix multiplication).

As both would be symmetric they'll both work; I'd guess you mean the product as that's what you used in the Linear Algebra with SciPy section.

**Comment by patrickwalls** [comment]
Thanks. I changed the text to match the code with S=PP^T.
